language: java
dist: trusty
script: ant all

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "/home/travis/build/Joffrey4/CompressedBlocksPlugin/out/artifacts/CompressedBlocksPlugin_jar"
  skip_cleanup: true
  on:
    tags: true