language: java
dist: trusty
script: mvn CompressedBlocksPlugin -B

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/CompressedBlocksPlugin-$TRAVIS_TAG.jar"
  skip_cleanup: true
  on:
    tags: true