name: CompressedBlocks
version: 1.3
author: Joffrey4 aka NycoDiValones
main: io.github.joffrey4.compressedblocks.Main
website: https://jbvn.me/cbp/
description: Save space in your chests by compressing your block !